apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-deployment
  labels:
    app: static-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
      - name: static-web
        image: rakeshramch/static-web:letast
        ports:
        - containerPort: 80
